// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Add");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, "Just concats two strings", React.createElement("div", undefined, React.createElement("input", {
                                  value: self[/* state */1][/* val1 */0],
                                  onChange: (function ($$event) {
                                      return Curry._1(self[/* send */3], /* ChangeValue1 */Block.__(0, [$$event.target.value]));
                                    })
                                }), React.createElement("input", {
                                  value: self[/* state */1][/* val2 */1],
                                  onChange: (function ($$event) {
                                      return Curry._1(self[/* send */3], /* ChangeValue2 */Block.__(1, [$$event.target.value]));
                                    })
                                }), React.createElement("div", undefined, React.createElement("button", {
                                      onClick: (function () {
                                          return Curry._1(self[/* send */3], /* Combine */0);
                                        })
                                    }, "Combine"), React.createElement("button", {
                                      onClick: (function () {
                                          return Curry._1(self[/* send */3], /* Clear */1);
                                        })
                                    }, "Clear")), React.createElement("div", undefined, self[/* state */1][/* result */2])));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* val1 */"",
                      /* val2 */"",
                      /* result */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action === 0) {
                  return /* Update */Block.__(0, [/* record */[
                              /* val1 */state[/* val1 */0],
                              /* val2 */state[/* val2 */1],
                              /* result */state[/* val1 */0] + state[/* val2 */1]
                            ]]);
                } else {
                  return /* Update */Block.__(0, [/* record */[
                              /* val1 */"",
                              /* val2 */"",
                              /* result */""
                            ]]);
                }
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* val1 */state[/* val1 */0],
                            /* val2 */action[0],
                            /* result */state[/* result */2]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* val1 */action[0],
                            /* val2 */state[/* val2 */1],
                            /* result */state[/* result */2]
                          ]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
