// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Add$ReactTemplate = require("./Add.bs.js");
var Heading$ReactTemplate = require("./Heading.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Heading$ReactTemplate.make("Ocaml and Reason React fanciness", /* array */[])), "index3");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Add$ReactTemplate.make(/* array */[])), "add");

/*  Not a pure module */
